// Dedicated analysis engine for HOA Navigator.
//
// HOA was previously handled as one of eleven `task` strings inside the
// shared api/_lib/navigator-engine.js. That generic path could not honour
// what hoa.html actually sells, in three specific ways:
//
//   1. The page promises "Every finding cites the page it came from" and
//      "top 5 concerns, each backed by a page-level citation". The generic
//      engine never enabled document citations and its shared schema had
//      no citation field, so any page number in a shipped report was the
//      model writing a number into a prose field — unverified.
//   2. The page sells an "HOA Risk Score — Low, Moderate, High, or
//      Critical". In the generic schema that was free text in
//      `headline_tag`, with no typed value anywhere.
//   3. Reserve analysis is arithmetic (percent funded, contribution
//      shortfall, per-unit exposure, projecting a reserve balance against
//      planned capital spend). The generic engine asked the model to do
//      that in its head. That is the same failure mode behind the
//      2026-08-31 purchase-engine incident, where the model reproducibly
//      tried to "show its work" by emitting simulated tool-call syntax
//      into a prose field. Patches 0004-0007 treated that with sanitizing,
//      prompt scolding and a thinking scratchpad; none of them gave it an
//      actual calculator.
//
// This engine addresses all three directly:
//
//   * Two passes. The EVIDENCE pass reads the documents with citations
//     enabled and code execution available, and writes a prose analysis.
//     The API attaches real citations (document index, page range, and the
//     exact quoted text) to the text blocks it returns — those are
//     generated by the citation system from the actual document, not
//     recalled by the model. We harvest them into a numbered evidence
//     table. The STRUCTURING pass then turns that narrative into the
//     report schema, and every finding must reference evidence by index.
//     We validate each index server-side and splice in the harvested
//     citation. A page number in a shipped report therefore comes from the
//     API, never from the model's own writing.
//   * A typed HOA schema with `strict: true`, so risk_score is a real enum
//     and the API guarantees the tool input validates. `strict` is also
//     why this file has no equivalent of navigator-engine's
//     TAG_LEAK_PATTERN regex and its retry loop — schema-invalid output is
//     rejected server-side rather than detected here after the fact.
//   * The code_execution tool, so reserve maths runs as real Python.
//
// Documents go through the Files API rather than being base64-inlined into
// the request. Inlining was at the edge of the 32MB request ceiling: the
// intake allows 4 files x 6MB, and 24MB of PDF base64-encodes to roughly
// 32.8MB, so a customer who uploaded the maximum the form permits could
// produce a request the API would reject. Uploaded files are deleted in a
// finally block — these are a named person's financial documents and there
// is no reason to leave them in the org's file store after the run.
//
// Requires the same ANTHROPIC_API_KEY the other engines use.

const AnthropicSDK = require('@anthropic-ai/sdk');
const Anthropic = AnthropicSDK.default || AnthropicSDK;
const { toFile } = AnthropicSDK;
const { getSupabaseAdmin } = require('./supabaseAdmin');

// Opus 5 rather than the Sonnet 5 the shared engine uses. On a $79 report
// backing a six-figure purchase decision the model-cost delta is roughly a
// dollar; the accuracy delta on dense financial documents is not.
const HOA_MODEL = 'claude-opus-5';

// Thinking is on by default on Opus 5 (omitting `thinking` runs adaptive),
// but it is set explicitly here so the intent survives future edits.
// `xhigh` is the recommended level for this kind of long-horizon
// analytical work. Note this engine never combines thinking with a forced
// tool_choice — the evidence pass uses no report tool at all, and the
// structuring pass uses tool_choice:'auto' plus an explicit instruction,
// which is what purchase-engine.js:390 had to work around.
const EFFORT = 'xhigh';

// Streaming, because max_tokens this large will otherwise hit the SDK's
// HTTP timeout on a long analytical turn.
const MAX_TOKENS_EVIDENCE = 32000;
const MAX_TOKENS_REPORT = 16000;

// Guards a runaway server-tool loop (pause_turn, or the model ending its
// turn without producing the report).
const MAX_TURNS = 8;

const REPORT_TOOL_NAME = 'submit_hoa_report';

const RISK_LEVELS = ['Low', 'Moderate', 'High', 'Critical'];
const LIKELIHOODS = ['Unlikely', 'Possible', 'Likely', 'Already announced', 'Cannot assess'];

// What actually predicts a special assessment. This is the domain content
// that makes the product worth $79 rather than a generic "review these
// documents" prompt, and it is deliberately expressed as signals to look
// for rather than as thresholds to apply mechanically.
const HOA_RUBRIC = `
SPECIAL-ASSESSMENT RISK — WHAT TO LOOK FOR

Reserve adequacy is the primary signal:
- Percent funded (reserve balance / fully funded balance). Below ~30% is
  widely treated as weak and is the classic precursor to a special
  assessment; ~30-70% is fair; above ~70% is strong. Report the actual
  computed figure, not the band alone.
- Whether the association is actually contributing what its own reserve
  study recommends annually. A study that recommends a contribution the
  budget does not fund is a shortfall compounding every year.
- Major components with little remaining useful life and no funded plan:
  roof, elevators, siding/cladding, plumbing risers, balconies/decks,
  paving, boilers, pool. A component due within the short-term window with
  a replacement cost far exceeding the reserve balance is the single
  strongest short-term signal.

Then the budget and governance signals:
- Operating deficit, or dues increases persistently below cost inflation
  (under-collecting now means assessing later).
- Owner delinquency rate — above roughly 5-10% strains collections.
- Any borrowing: a bank loan, a line of credit, or a reserve "loan" to the
  operating fund. Associations frequently borrow immediately before, or
  instead of, assessing.
- Insurance: a large or percentage-based deductible, a non-renewal, a
  named-storm or earthquake deductible, or a coverage gap. An uninsured
  loss is assessed to owners.
- Litigation, construction-defect claims, or a settlement.
- Statutory drivers where the documents show the property is subject to
  them — e.g. Florida structural integrity reserve study and reserve-
  funding requirements post-Surfside, California balcony/exterior element
  inspections. Only raise these when the documents indicate the property
  is actually in that jurisdiction.

Meeting minutes are the highest-signal document for imminent action.
Language such as "special assessment", "reserve study update", "loan",
"line of credit", "deferred", "emergency repair", "engineer's report", or
a discussion of funding options is often the earliest warning available,
and predates any formal notice the seller would have to disclose.

Short-term means the next 12 months. Mid-term means one to five years.
Assess these separately — they frequently differ, and a buyer waiving a
contingency cares most about the short-term window.
`.trim();

const HONESTY_RULES = `
GROUNDING RULES

Every factual claim about this association must come from the documents
provided. You have no access to this HOA's records beyond these files, no
live database, and no ability to look the association up.

- Never state a dollar figure that is not either read directly from a
  document or computed from figures that were. When you compute one, say
  what it was computed from.
- Never infer a document you were not given. If there is no reserve study,
  say the reserve study is missing — do not reason as though you had one.
- Distinguish clearly between what a document states, what you calculated,
  and what you are inferring. Inference is allowed and often useful; it
  must be labelled.
- If the documents do not support a view on something, say so. An honest
  "cannot assess from what was provided" is more valuable to a buyer about
  to waive a contingency than a confident guess, and this product's own
  marketing promises the report will not manufacture concerns that are not
  there. A genuinely healthy association must be reported as healthy.
- Do not give legal advice or tell the buyer whether to purchase. Assess
  the association's finances and governance, and give them the questions
  to ask.
`.trim();

const EVIDENCE_SYSTEM = `You are the analysis engine behind HOA Navigator. A homebuyer, usually still inside their contingency period, has paid for an assessment of whether the HOA they are buying into is likely to levy a special assessment in the short term (next 12 months) or mid term (1-5 years).

You have been given whatever HOA documents the buyer could obtain — commonly some subset of budget, reserve study, meeting minutes, assessment notices, insurance summary, and bylaws. Work with what is actually present and be explicit about what is missing.

${HOA_RUBRIC}

${HONESTY_RULES}

USING THE CALCULATOR

You have a code execution tool. Use it for every non-trivial calculation:
percent funded, annual contribution versus the study's recommendation,
per-unit exposure, cumulative shortfall, and any projection of the reserve
balance against planned capital spending. Do not perform multi-step
arithmetic in your head or in prose. Run it, then state the result.

CITING

Citations are enabled on the documents. When you make a claim that rests on
something in a document, quote the specific passage it comes from so the
citation attaches to it. Quote the narrowest passage that actually supports
the claim — a line from a reserve table, the sentence in the minutes, the
figure in the budget. Broad citations spanning many pages are not useful to
a buyer who needs to verify the finding.

WHAT TO WRITE NOW

Write a thorough analytical narrative covering: which documents you
received and which are missing; reserve adequacy with the numbers computed;
the capital projects ahead and how they are funded; short-term special-
assessment risk; mid-term special-assessment risk; insurance; governance,
litigation and anything visible in the minutes; and your overall risk read.

This narrative is an internal working pass — it will be structured into the
customer's report afterwards. Prioritise completeness, explicit numbers, and
tight quotation over presentation.`;

const REPORT_SYSTEM = `You are formatting a completed HOA risk analysis into the structured report a customer receives.

You will be given your own analysis narrative and a numbered EVIDENCE TABLE. Each evidence item is a verified citation captured from the source documents: its document title, page range, and the exact quoted text.

Rules for this pass:

- Do not introduce any new factual claim, number, or concern that is not in the narrative. This is a formatting pass, not further analysis.
- Every entry in "findings" must cite evidence by index using evidence_ids. Use the indices from the EVIDENCE TABLE exactly. Never invent an index, and never write a page number into any text field — page numbers are attached automatically from the evidence table.
- Order findings by how much they should matter to a buyer deciding whether to waive their contingency, most important first.
- The customer is an ordinary homebuyer, not an accountant. Write plainly. Keep the specific numbers, drop the jargon.
- Where a field does not apply, use an empty string or an empty array. Do not invent filler.

Respond by calling the ${REPORT_TOOL_NAME} tool.`;

// Superset schema: the generic fields navigator-status.html already renders
// (headline / headline_tag / summary / key_numbers / sections /
// missing_or_uncertain / closing_*) plus the HOA-specific typed fields. The
// existing renderer keeps working untouched; the HOA additions render
// through a progressive-enhancement block.
//
// strict:true requires additionalProperties:false and that every property
// be listed in `required` — hence the instruction above to use an empty
// string or empty array rather than omitting a field.
const REPORT_TOOL = {
  name: REPORT_TOOL_NAME,
  description: 'Submit the structured HOA risk report for this submission.',
  strict: true,
  input_schema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      risk_score: {
        type: 'string',
        enum: RISK_LEVELS,
        description: 'The overall HOA Risk Score.',
      },
      risk_rationale: {
        type: 'string',
        description: 'Two to four sentences on why this score and not the one above or below it.',
      },
      headline: {
        type: 'string',
        description: 'The single most important thing this buyer needs to know, in plain English. A verdict, not a restatement of the product name.',
      },
      headline_tag: {
        type: 'string',
        description: 'Short badge, e.g. "Moderate risk". Normally the risk score followed by the word risk.',
      },
      summary: {
        type: 'string',
        description: 'Two to four sentences: the bottom line and why.',
      },
      short_term_risk: {
        type: 'object',
        additionalProperties: false,
        description: 'Special-assessment risk over the next 12 months.',
        properties: {
          likelihood: { type: 'string', enum: LIKELIHOODS },
          rationale: { type: 'string' },
          estimated_per_unit_low: { type: 'string', description: 'Low end of estimated per-unit exposure as a plain dollar string, or empty string if it cannot be estimated from the documents.' },
          estimated_per_unit_high: { type: 'string', description: 'High end, or empty string.' },
          basis: { type: 'string', description: 'What that estimate was computed from, or why no estimate is possible.' },
          evidence_ids: { type: 'array', items: { type: 'integer' } },
        },
        required: ['likelihood', 'rationale', 'estimated_per_unit_low', 'estimated_per_unit_high', 'basis', 'evidence_ids'],
      },
      mid_term_risk: {
        type: 'object',
        additionalProperties: false,
        description: 'Special-assessment risk over one to five years.',
        properties: {
          likelihood: { type: 'string', enum: LIKELIHOODS },
          rationale: { type: 'string' },
          estimated_per_unit_low: { type: 'string' },
          estimated_per_unit_high: { type: 'string' },
          basis: { type: 'string' },
          evidence_ids: { type: 'array', items: { type: 'integer' } },
        },
        required: ['likelihood', 'rationale', 'estimated_per_unit_low', 'estimated_per_unit_high', 'basis', 'evidence_ids'],
      },
      reserve_health: {
        type: 'object',
        additionalProperties: false,
        description: 'Reserve position. Use empty strings where the documents do not support a figure.',
        properties: {
          percent_funded: { type: 'string', description: 'Computed percent funded, e.g. "34%", or empty string if not determinable.' },
          reserve_balance: { type: 'string' },
          fully_funded_balance: { type: 'string' },
          annual_contribution: { type: 'string' },
          recommended_contribution: { type: 'string' },
          assessment: { type: 'string', description: 'Plain-English read on what this reserve position means for the buyer.' },
          evidence_ids: { type: 'array', items: { type: 'integer' } },
        },
        required: ['percent_funded', 'reserve_balance', 'fully_funded_balance', 'annual_contribution', 'recommended_contribution', 'assessment', 'evidence_ids'],
      },
      findings: {
        type: 'array',
        description: 'The buyer’s top concerns, most important first. Five or fewer unless the documents genuinely support more.',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            concern: { type: 'string', description: 'The concern in one short line.' },
            severity: { type: 'string', enum: RISK_LEVELS },
            detail: { type: 'string', description: 'What was found and why it matters to this buyer. No page numbers — those attach from the evidence.' },
            evidence_ids: { type: 'array', items: { type: 'integer' } },
          },
          required: ['concern', 'severity', 'detail', 'evidence_ids'],
        },
      },
      key_numbers: {
        type: 'array',
        description: 'Up to six headline numbers for the report header.',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            label: { type: 'string' },
            value: { type: 'string' },
          },
          required: ['label', 'value'],
        },
      },
      sections: {
        type: 'array',
        description: 'Report body as labelled sections, rendered by the existing generic renderer.',
        items: {
          type: 'object',
          additionalProperties: false,
          properties: {
            icon: { type: 'string', description: 'A single emoji, or empty string.' },
            title: { type: 'string' },
            items: { type: 'array', items: { type: 'string' } },
          },
          required: ['icon', 'title', 'items'],
        },
      },
      documents_reviewed: {
        type: 'array',
        items: { type: 'string' },
        description: 'The documents actually provided and read.',
      },
      documents_missing: {
        type: 'array',
        items: { type: 'string' },
        description: 'Typically-useful HOA documents that were NOT provided and are worth requesting before the contingency expires.',
      },
      questions_for_hoa: {
        type: 'array',
        items: { type: 'string' },
        description: 'Specific questions to send the HOA, seller, or agent — each one answerable and tied to something in this analysis.',
      },
      missing_or_uncertain: {
        type: 'array',
        items: { type: 'string' },
        description: 'Anything that could not be verified, or where the report is inferring rather than reading. Empty array only if there is genuinely nothing to flag.',
      },
      closing_title: { type: 'string', description: 'Title for the closing block, normally the pre-contingency checklist.' },
      closing_body: { type: 'string', description: 'The pre-contingency-expiration checklist as plain text with line breaks.' },
    },
    required: [
      'risk_score', 'risk_rationale', 'headline', 'headline_tag', 'summary',
      'short_term_risk', 'mid_term_risk', 'reserve_health', 'findings',
      'key_numbers', 'sections', 'documents_reviewed', 'documents_missing',
      'questions_for_hoa', 'missing_or_uncertain', 'closing_title', 'closing_body',
    ],
  },
};

function guessMediaType(filename) {
  const ext = String(filename).toLowerCase().split('.').pop();
  if (ext === 'pdf') return 'application/pdf';
  if (ext === 'png') return 'image/png';
  if (ext === 'webp') return 'image/webp';
  if (ext === 'gif') return 'image/gif';
  if (ext === 'heic' || ext === 'heif') return 'image/heic';
  return 'image/jpeg';
}

function basename(path) {
  const parts = String(path).split('/');
  return parts[parts.length - 1] || String(path);
}

// Pull the API-generated citations off the response's text blocks. These
// are produced by the citation system from the source document — the page
// numbers and cited_text are not model-authored, which is the entire point
// of running the evidence pass separately. Deduplicated, because the model
// will often cite the same passage supporting several claims.
function harvestCitations(content) {
  const seen = new Map();
  for (const block of content || []) {
    if (block.type !== 'text' || !Array.isArray(block.citations)) continue;
    for (const c of block.citations) {
      const pageStart = c.start_page_number != null ? c.start_page_number : null;
      const pageEnd = c.end_page_number != null ? c.end_page_number : null;
      const key = [c.document_index, c.document_title, pageStart, pageEnd, c.cited_text].join('|');
      if (seen.has(key)) continue;
      seen.set(key, {
        document_title: c.document_title || null,
        document_index: c.document_index != null ? c.document_index : null,
        page_start: pageStart,
        page_end: pageEnd,
        cited_text: (c.cited_text || '').trim(),
      });
    }
  }
  return Array.from(seen.values());
}

function formatEvidenceTable(evidence) {
  if (!evidence.length) {
    return 'EVIDENCE TABLE\n\n(No citations were captured. Do not cite any evidence ids — leave every evidence_ids array empty, and say plainly in missing_or_uncertain that findings could not be tied to specific pages.)';
  }
  const rows = evidence.map((e, i) => {
    const pages = e.page_start
      ? (e.page_end && e.page_end !== e.page_start ? `pp. ${e.page_start}-${e.page_end}` : `p. ${e.page_start}`)
      : 'page unknown';
    return `[${i}] ${e.document_title || 'Untitled document'} (${pages})\n    "${e.cited_text.slice(0, 600)}"`;
  });
  return `EVIDENCE TABLE\n\n${rows.join('\n\n')}`;
}

function textOf(content) {
  return (content || [])
    .filter((b) => b.type === 'text')
    .map((b) => b.text)
    .join('\n')
    .trim();
}

// Replace every evidence_ids array in the report with the actual harvested
// citations, dropping any index the model made up. This is what makes the
// shipped page numbers trustworthy: they are copied out of the harvested
// table, never read from what the model wrote.
function attachCitations(report, evidence) {
  let dropped = 0;

  function resolve(ids) {
    const out = [];
    for (const id of Array.isArray(ids) ? ids : []) {
      const item = evidence[id];
      if (!item) { dropped++; continue; }
      out.push(item);
    }
    return out;
  }

  function walk(node) {
    if (Array.isArray(node)) { node.forEach(walk); return; }
    if (!node || typeof node !== 'object') return;
    if (Object.prototype.hasOwnProperty.call(node, 'evidence_ids')) {
      node.citations = resolve(node.evidence_ids);
      delete node.evidence_ids;
    }
    Object.values(node).forEach(walk);
  }

  walk(report);
  return { report, droppedCitationRefs: dropped };
}

// Runs a request to completion, continuing through pause_turn (which the
// server-side code execution tool can produce on a long turn) and nudging
// once if the model ends its turn without calling the report tool.
async function runToCompletion(client, { system, messages, tools, maxTokens, expectToolName }) {
  const working = messages.slice();

  for (let turn = 0; turn < MAX_TURNS; turn++) {
    const request = {
      model: HOA_MODEL,
      max_tokens: maxTokens,
      system,
      thinking: { type: 'adaptive' },
      output_config: { effort: EFFORT },
      messages: working,
    };
    if (tools) {
      request.tools = tools;
      // Deliberately not a forced tool_choice. Forcing the tool conflicts
      // with thinking (see purchase-engine.js:390), and 'auto' plus an
      // explicit instruction in the system prompt achieves the same thing
      // without that constraint.
      request.tool_choice = { type: 'auto' };
    }

    const response = await client.messages.stream(request).finalMessage();

    if (response.stop_reason === 'refusal') {
      const detail = response.stop_details ? ` (${response.stop_details.category})` : '';
      throw new Error(`Model declined to complete the analysis${detail}`);
    }

    if (expectToolName) {
      const toolUse = response.content.find(
        (b) => b.type === 'tool_use' && b.name === expectToolName,
      );
      if (toolUse) return { toolInput: toolUse.input, response };
    }

    if (response.stop_reason === 'pause_turn') {
      working.push({ role: 'assistant', content: response.content });
      continue;
    }

    if (!expectToolName) return { response };

    // Ended its turn without producing the report. Ask once, explicitly.
    working.push({ role: 'assistant', content: response.content });
    working.push({
      role: 'user',
      content: `Call the ${expectToolName} tool now with the structured report.`,
    });
  }

  throw new Error(`Analysis did not complete within ${MAX_TURNS} turns`);
}

async function generateHoaReport(submissionId) {
  const admin = getSupabaseAdmin();

  const { data: submission, error: fetchError } = await admin
    .from('navigator_submissions')
    .select('*')
    .eq('id', submissionId)
    .single();

  if (fetchError || !submission) throw new Error('Submission not found');

  await admin
    .from('navigator_submissions')
    .update({ status: 'processing', updated_at: new Date().toISOString() })
    .eq('id', submissionId);

  const uploadedFileIds = [];
  let client = null;

  try {
    const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
    if (!ANTHROPIC_API_KEY) throw new Error('Missing ANTHROPIC_API_KEY env var');
    client = new Anthropic({ apiKey: ANTHROPIC_API_KEY });

    const filePaths = submission.file_paths || [];
    if (!filePaths.length) {
      throw new Error('HOA Navigator requires at least one uploaded document, but none were found on this submission.');
    }

    // Supabase -> Files API. Referencing by file_id instead of inlining
    // base64 keeps the request well under the 32MB ceiling that 4 x 6MB of
    // PDF would otherwise breach once encoded.
    const documentBlocks = [];
    for (const path of filePaths) {
      const { data: fileBlob, error: downloadError } = await admin.storage
        .from('navigator-uploads')
        .download(path);
      if (downloadError || !fileBlob) continue;

      const mediaType = guessMediaType(path);
      const filename = basename(path);
      const buffer = Buffer.from(await fileBlob.arrayBuffer());

      const uploaded = await client.files.upload({
        file: await toFile(buffer, filename, { type: mediaType }),
      });
      uploadedFileIds.push(uploaded.id);

      if (mediaType === 'application/pdf') {
        documentBlocks.push({
          type: 'document',
          source: { type: 'file', file_id: uploaded.id },
          title: filename,
          citations: { enabled: true },
        });
      } else {
        // Images cannot carry citations. They are still worth reading (an
        // assessment notice photographed on a phone is a real case), but
        // findings resting on them will have no evidence to reference,
        // which the model is told to flag.
        documentBlocks.push({
          type: 'image',
          source: { type: 'file', file_id: uploaded.id },
        });
      }
    }

    if (!documentBlocks.length) {
      throw new Error('Could not read any of the attached documents for this submission.');
    }

    // hoa.html submits exactly one optional free-text field
    // (#intake-description, sent as form_data.description). It is where a
    // buyer typically supplies unit count, build year, and what the seller
    // has claimed — all of which matter to per-unit exposure and are worth
    // weighing against the documents rather than taking at face value.
    const formData = submission.form_data || {};
    const contextLines = [
      formData.description
        ? `What the buyer told us (their words, not verified — check it against the documents): ${formData.description}`
        : 'The buyer did not add any description of the property.',
      `Documents attached: ${documentBlocks.length} (${filePaths.map(basename).join(', ')})`,
      documentBlocks.some((b) => b.type === 'image')
        ? 'Note: at least one upload is an image rather than a PDF. Images cannot produce page citations — say so if a finding rests on one.'
        : null,
    ].filter(Boolean).join('\n');

    // Pass 1 — evidence. Documents in, citations on, calculator available,
    // no report tool. The output we care about is the narrative plus the
    // citations the API attaches to it.
    const { response: evidenceResponse } = await runToCompletion(client, {
      system: EVIDENCE_SYSTEM,
      maxTokens: MAX_TOKENS_EVIDENCE,
      tools: [{ type: 'code_execution_20260521', name: 'code_execution' }],
      messages: [{
        role: 'user',
        content: [...documentBlocks, { type: 'text', text: contextLines }],
      }],
    });

    const narrative = textOf(evidenceResponse.content);
    if (!narrative) throw new Error('Evidence pass produced no analysis text');

    const evidence = harvestCitations(evidenceResponse.content);

    // Pass 2 — structuring. No documents, so this is cheap; the model is
    // reformatting its own narrative against the verified evidence table.
    const { toolInput } = await runToCompletion(client, {
      system: REPORT_SYSTEM,
      maxTokens: MAX_TOKENS_REPORT,
      tools: [REPORT_TOOL],
      expectToolName: REPORT_TOOL_NAME,
      messages: [{
        role: 'user',
        content: `ANALYSIS NARRATIVE\n\n${narrative}\n\n---\n\n${formatEvidenceTable(evidence)}`,
      }],
    });

    const { report, droppedCitationRefs } = attachCitations(toolInput, evidence);

    report.evidence = evidence;
    report.generated_at = new Date().toISOString();
    report.disclaimer = 'This is an analysis of the documents provided, not legal, financial, or investment advice, and not a substitute for review by an attorney, accountant, or licensed inspector. Dollar figures are estimates unless quoted directly from a document. Verify anything you intend to rely on before waiving a contingency.';

    await admin.from('navigator_reports').insert({
      submission_id: submissionId,
      product: 'hoa',
      report_json: report,
      model: HOA_MODEL,
    });

    await admin
      .from('navigator_submissions')
      .update({ status: 'complete', updated_at: new Date().toISOString() })
      .eq('id', submissionId);

    if (droppedCitationRefs > 0) {
      console.warn(`[hoa-engine] submission ${submissionId}: dropped ${droppedCitationRefs} invalid citation reference(s)`);
    }

    return report;
  } catch (err) {
    await admin
      .from('navigator_submissions')
      .update({ status: 'failed', error: String(err.message || err).slice(0, 500), updated_at: new Date().toISOString() })
      .eq('id', submissionId);
    throw err;
  } finally {
    // The buyer's HOA documents have no reason to persist in the file
    // store once the report exists. Failures here must not mask a real
    // error from the try block.
    if (client && uploadedFileIds.length) {
      await Promise.all(uploadedFileIds.map((id) =>
        client.files.delete(id).catch((e) => {
          console.warn(`[hoa-engine] could not delete file ${id}: ${e.message}`);
        }),
      ));
    }
  }
}

module.exports = {
  generateHoaReport,
  // Exported for tests.
  harvestCitations,
  attachCitations,
  formatEvidenceTable,
  REPORT_TOOL,
  RISK_LEVELS,
  LIKELIHOODS,
  HOA_MODEL,
};
