// Builds a plain, readable PDF version of a completed Navigator report —
// the same generic shape api/_lib/navigator-engine.js and
// api/_lib/purchase-engine.js both already produce (headline, summary,
// key_numbers, sections, missing_or_uncertain), the exact shape
// navigator-status.html renders in the browser. Added 2026-09-01 so a
// customer can get a copy emailed to them instead of only ever viewing it
// on that one page/device.
//
// Uses pdfkit (pure JavaScript, no native dependencies — safe in Vercel's
// serverless environment) rather than a headless-browser HTML-to-PDF
// approach, which would be much heavier for a plain, text-focused document
// like this one.

const PDFDocument = require('pdfkit');

const COLORS = {
  heading: '#1F1B16',
  body: '#3A342B',
  muted: '#7A7163',
  accent: '#4FB6E8',
};

function addWrappedText(doc, text, options) {
  doc.fillColor(COLORS.body).fontSize(11).text(text, options);
}

// Returns a Promise<Buffer> — pdfkit is a stream-based API, so this
// collects the generated chunks itself rather than exposing a stream to
// every caller.
function buildReportPdfBuffer(report, meta) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 56, size: 'LETTER' });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fillColor(COLORS.accent).fontSize(10).text('STREAMNAVIGATOR', { characterSpacing: 1.5 });
      doc.moveDown(0.3);
      doc.fillColor(COLORS.heading).fontSize(18).font('Helvetica-Bold').text(report.headline || 'Your report', { width: 500 });
      if (report.headline_tag) {
        doc.moveDown(0.2);
        doc.fillColor(COLORS.accent).fontSize(10).font('Helvetica-Bold').text(String(report.headline_tag).toUpperCase());
      }
      doc.moveDown(0.6);

      if (report.summary) {
        addWrappedText(doc, report.summary, { width: 500 });
        doc.moveDown(1);
      }

      // Key numbers, as a simple two-column list rather than trying to
      // replicate the card-grid layout from the web page — a PDF is read
      // linearly, not scanned the way a webpage grid is.
      if (Array.isArray(report.key_numbers) && report.key_numbers.length) {
        doc.fillColor(COLORS.heading).fontSize(13).font('Helvetica-Bold').text('Key numbers');
        doc.moveDown(0.3);
        report.key_numbers.forEach((n) => {
          doc.fillColor(COLORS.muted).fontSize(10).font('Helvetica-Bold').text(String(n.label || ''), { continued: false });
          doc.fillColor(COLORS.body).fontSize(11).font('Helvetica').text(String(n.value || ''));
          doc.moveDown(0.3);
        });
        doc.moveDown(0.5);
      }

      // Sections
      (report.sections || []).forEach((section) => {
        if (doc.y > 680) doc.addPage();
        // pdfkit's built-in Helvetica font has no emoji glyphs — the
        // section icons (💰, 🏦, etc.) rendered as garbage characters when
        // included directly, caught by actually rendering a sample PDF to
        // an image and looking at it rather than just checking the byte
        // count. Titles alone read perfectly fine without the icon.
        const title = section.title || '';
        doc.fillColor(COLORS.heading).fontSize(13).font('Helvetica-Bold').text(title, { width: 500 });
        doc.moveDown(0.25);
        (section.items || []).forEach((item) => {
          addWrappedText(doc, String(item), { width: 500 });
          doc.moveDown(0.3);
        });
        doc.moveDown(0.4);
      });

      if (Array.isArray(report.missing_or_uncertain) && report.missing_or_uncertain.length) {
        if (doc.y > 650) doc.addPage();
        doc.fillColor(COLORS.heading).fontSize(13).font('Helvetica-Bold').text('What we couldn\'t verify');
        doc.moveDown(0.25);
        report.missing_or_uncertain.forEach((item) => {
          addWrappedText(doc, `•  ${item}`, { width: 500 });
          doc.moveDown(0.25);
        });

        // Surface-specific: a PDF has no input box, so it points at the place
        // that does rather than telling the reader to type something here.
        doc.moveDown(0.25);
        addWrappedText(
          doc,
          'Any figures we could not read can be entered on your online report, and we will rebuild it with them included.',
          { width: 500 }
        );
      }

      // Footer — checked against remaining space first so a two-line
      // footer can't get split with one line stranded on an otherwise
      // blank extra page (caught by rendering this to an image and
      // actually looking, not just checking that a PDF came out).
      if (doc.y > 700) doc.addPage();
      doc.moveDown(1);
      doc.fillColor(COLORS.muted).fontSize(8).font('Helvetica').text(
        `Generated by StreamNavigator${meta && meta.generatedAt ? ' on ' + meta.generatedAt : ''}. This analysis is directional, not financial advice — see the full report online for sourcing details.`,
        { width: 500 }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { buildReportPdfBuffer };
