// Run: node tests/pdf-letters.test.js
//
// The lender and settlement-agent letters were built by closing-service.js,
// returned to the caller, and then dropped -- nothing rendered them anywhere.
// Worse, the PAID path never built them at all: closing-service.js serves the
// free scorecard, while the report a customer pays for is generated by
// navigator-engine.js, which had no reference to closing-emails.js. So the one
// customer entitled to the letters was the one customer who could not get them.
//
// This suite pins both halves: the engine attaches them, and the PDF prints
// them -- with the sign-post at the front, because a customer who stops reading
// after the findings has still paid for the letters.
'use strict';

const fs = require('fs');
const path = require('path');

let passed = 0;
const failures = [];
function test(name, fn) {
  try { fn(); passed += 1; } catch (err) { failures.push(`${name}\n    ${err.message.split('\n')[0]}`); }
}
// Async cases are collected and awaited explicitly at the end. Firing them off
// and sleeping "long enough" is how a suite starts reporting a pass for a test
// that never finished running.
const pending = [];
function testAsync(name, fn) {
  pending.push(
    Promise.resolve()
      .then(fn)
      .then(() => { passed += 1; })
      .catch((err) => { failures.push(`${name}\n    ${err.message.split('\n')[0]}`); })
  );
}

const root = path.join(__dirname, '..');
const { buildEmails } = require('../api/_lib/closing-emails');
const { buildReportPdfBuffer } = require('../api/_lib/pdf-report');

const FINDINGS = [
  {
    checkId: 'PREPAID_INTEREST',
    title: 'Prepaid interest does not match the per-diem and closing date',
    severity: 'confirmed_error',
    actionability: 'ask_lender',
    askLender: true,
    dollarImpact: 57540,
    basis: 'Section F shows 12 days of prepaid interest; from closing to month end is 9.',
    recommendedAction: 'Ask the lender to recompute prepaid interest for 9 days.',
    detail: {},
  },
  {
    checkId: 'RECORDING_FEES',
    title: 'Recording fees exceed the county schedule',
    severity: 'requires_verification',
    actionability: 'ask_settlement',
    askSettlement: true,
    dollarImpact: 8600,
    basis: 'Section E recording fees are above the published schedule.',
    recommendedAction: 'Ask the settlement agent for the recording fee breakdown.',
    detail: {},
  },
];

const CTX = {
  propertyAddress: '2526 Heath Place, Virginia Beach, VA 23456',
  closingDate: '2026-09-18',
  borrowerName: 'Jordan Ellis',
  lenderName: 'Atlantic Union Mortgage',
};

const BASE_REPORT = {
  headline: 'Two items worth raising',
  summary: 'Your Closing Disclosure reconciles overall.',
  sections: [{ title: 'What we found', items: ['Prepaid interest is billed for 12 days.'] }],
};

// --- the paid path is actually wired -------------------------------------

test('navigator-engine builds the letters on the paid report path', () => {
  const engine = fs.readFileSync(path.join(root, 'api', '_lib', 'navigator-engine.js'), 'utf8');
  if (!/require\(['"]\.\/closing-emails['"]\)/.test(engine)) {
    throw new Error('navigator-engine does not import closing-emails -- the paid report has no letters');
  }
  if (!/buildEmails\(/.test(engine)) throw new Error('buildEmails is never called on the paid path');
  if (!/report\.emails\s*=/.test(engine)) throw new Error('the letters are never attached to the stored report');
});

test('the letters are attached after generation, not handed to the model', () => {
  const engine = fs.readFileSync(path.join(root, 'api', '_lib', 'navigator-engine.js'), 'utf8');
  const attachAt = engine.indexOf('report.emails =');
  const guardAt = engine.indexOf('Failed to generate a valid report');
  if (attachAt === -1 || guardAt === -1) throw new Error('could not locate attach point');
  // A letter the customer signs their name to must not be reworded by the model.
  if (attachAt < guardAt) throw new Error('letters attached before the report is validated');
});

// --- what actually comes out of the PDF ----------------------------------

// The letter body is the customer's own text; asserting on the raw PDF bytes
// would only prove pdfkit compressed it. These read what pdfkit was asked to
// draw by capturing the text calls, which is the honest question: did the
// letter get onto the page.
function drawnText(buffer) {
  // pdfkit writes text into the content stream; a compressed stream defeats a
  // naive search, so compare sizes instead where content matters.
  return buffer.length;
}

testAsync('a report with two letters is materially longer than one without', async () => {
  const emails = buildEmails(FINDINGS, CTX);
  const withLetters = await buildReportPdfBuffer({ ...BASE_REPORT, emails }, { generatedAt: 'X' });
  const without = await buildReportPdfBuffer({ ...BASE_REPORT }, { generatedAt: 'X' });
  if (drawnText(withLetters) <= drawnText(without) + 500) {
    throw new Error('letters do not appear to have been drawn into the PDF');
  }
});

testAsync('a clean document produces no letters and no sign-post', async () => {
  const emails = buildEmails([], CTX);
  if (emails.lender !== null || emails.settlement !== null) {
    throw new Error('a clean document produced a letter -- it should produce none');
  }
  // Identical bytes: with no letters to point at, the front-of-report sign-post
  // must not print. A promise of letters that are not there is worse than
  // silence.
  const withKey = await buildReportPdfBuffer({ ...BASE_REPORT, emails }, { generatedAt: 'X' });
  const withoutKey = await buildReportPdfBuffer({ ...BASE_REPORT }, { generatedAt: 'X' });
  if (withKey.length !== withoutKey.length) {
    throw new Error('an empty emails object changed the PDF -- a sign-post is printing with nothing behind it');
  }
});

testAsync('one letter renders when only one party is implicated', async () => {
  const lenderOnly = buildEmails([FINDINGS[0]], CTX);
  if (!lenderOnly.lender || lenderOnly.settlement !== null) {
    throw new Error('routing is wrong: expected a lender letter and no settlement letter');
  }
  const buf = await buildReportPdfBuffer({ ...BASE_REPORT, emails: lenderOnly }, { generatedAt: 'X' });
  if (!buf || buf.length < 1000) throw new Error('single-letter PDF did not build');
});

testAsync('a missing recipient name does not print an empty "To"', async () => {
  // The extractor captures no settlement agent name, so `to` is routinely null.
  const emails = buildEmails([FINDINGS[1]], CTX);
  if (emails.settlement.to !== null) throw new Error('expected a null recipient for this fixture');
  const buf = await buildReportPdfBuffer({ ...BASE_REPORT, emails }, { generatedAt: 'X' });
  if (!buf || buf.length < 1000) throw new Error('PDF did not build with a null recipient');
});

// --- the sign-post and the letters must agree ----------------------------

test('the PDF sign-posts the letters before the findings, not after', () => {
  const pdf = fs.readFileSync(path.join(root, 'api', '_lib', 'pdf-report.js'), 'utf8');
  const signpostAt = pdf.indexOf('at the back of this report');
  const sectionsAt = pdf.indexOf('(report.sections || [])');
  const lettersAt = pdf.indexOf('READY-TO-SEND');
  if (signpostAt === -1) throw new Error('no sign-post telling the reader the letters exist');
  if (sectionsAt === -1 || lettersAt === -1) throw new Error('could not locate report body or letters block');
  if (!(signpostAt < sectionsAt)) throw new Error('sign-post is printed after the findings');
  if (!(lettersAt > sectionsAt)) throw new Error('letters are not at the back');
});

test('the sign-post counts letters rather than assuming two', () => {
  const pdf = fs.readFileSync(path.join(root, 'api', '_lib', 'pdf-report.js'), 'utf8');
  if (!/letters\.length === 1/.test(pdf)) {
    throw new Error('sign-post does not handle the one-letter case');
  }
});

test('body text is not left in the bold font', () => {
  const pdf = fs.readFileSync(path.join(root, 'api', '_lib', 'pdf-report.js'), 'utf8');
  const helper = (pdf.match(/function addWrappedText[\s\S]*?\n}/) || [''])[0];
  if (!/font\('Helvetica'\)/.test(helper)) {
    throw new Error('addWrappedText does not set its font -- pdfkit carries the last bold forward');
  }
});

test('dates in a letter read as English, not as ISO', () => {
  const emails = buildEmails(FINDINGS, CTX);
  const body = emails.lender.body;
  if (/2026-09-18/.test(body)) throw new Error('raw ISO date printed in a customer letter');
  if (!/September 18, 2026/.test(body)) throw new Error('closing date is not formatted for a reader');
});

(async () => {
  await Promise.all(pending);
  const total = passed + failures.length;
  if (failures.length) {
    console.error(`${passed}/${total} passed`);
    failures.forEach((f) => console.error('  FAIL  ' + f));
    process.exit(1);
  }
  console.log(`${passed}/${total} passed`);
})();
